swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /campo/:
    get:
      tags:
      - campo
      description: get Campo
      operationId: CampoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Campo'
        "403":
          description: ""
    post:
      tags:
      - campo
      description: create Campo
      operationId: CampoController.Post
      parameters:
      - in: body
        name: body
        description: body for Campo content
        required: true
        schema:
          $ref: '#/definitions/models.Campo'
      responses:
        "201":
          description: '{int} models.Campo'
        "403":
          description: body is empty
  /campo/{id}:
    get:
      tags:
      - campo
      description: get Campo by id
      operationId: CampoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Campo'
        "403":
          description: :id is empty
    put:
      tags:
      - campo
      description: update the Campo
      operationId: CampoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Campo content
        required: true
        schema:
          $ref: '#/definitions/models.Campo'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Campo'
        "403":
          description: :id is not int
    delete:
      tags:
      - campo
      description: delete the Campo
      operationId: CampoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /formulario/:
    get:
      tags:
      - formulario
      description: get Formulario
      operationId: FormularioController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulario'
        "403":
          description: ""
    post:
      tags:
      - formulario
      description: create Formulario
      operationId: FormularioController.Post
      parameters:
      - in: body
        name: body
        description: body for Formulario content
        required: true
        schema:
          $ref: '#/definitions/models.Formulario'
      responses:
        "201":
          description: '{int} models.Formulario'
        "403":
          description: body is empty
  /formulario/{id}:
    get:
      tags:
      - formulario
      description: get Formulario by id
      operationId: FormularioController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulario'
        "403":
          description: :id is empty
    put:
      tags:
      - formulario
      description: update the Formulario
      operationId: FormularioController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Formulario content
        required: true
        schema:
          $ref: '#/definitions/models.Formulario'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Formulario'
        "403":
          description: :id is not int
    delete:
      tags:
      - formulario
      description: delete the Formulario
      operationId: FormularioController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /tipo_estado/:
    get:
      tags:
      - tipo_estado
      description: get TipoEstado
      operationId: TipoEstadoController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoEstado'
        "403":
          description: ""
    post:
      tags:
      - tipo_estado
      description: create TipoEstado
      operationId: TipoEstadoController.Post
      parameters:
      - in: body
        name: body
        description: body for TipoEstado content
        required: true
        schema:
          $ref: '#/definitions/models.TipoEstado'
      responses:
        "201":
          description: '{int} models.TipoEstado'
        "403":
          description: body is empty
  /tipo_estado/{id}:
    get:
      tags:
      - tipo_estado
      description: get TipoEstado by id
      operationId: TipoEstadoController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoEstado'
        "403":
          description: :id is empty
    put:
      tags:
      - tipo_estado
      description: update the TipoEstado
      operationId: TipoEstadoController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TipoEstado content
        required: true
        schema:
          $ref: '#/definitions/models.TipoEstado'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoEstado'
        "403":
          description: :id is not int
    delete:
      tags:
      - tipo_estado
      description: delete the TipoEstado
      operationId: TipoEstadoController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.Campo:
    title: Campo
    type: object
    properties:
      Id:
        type: integer
        format: int64
      IdFormulario:
        $ref: '#/definitions/models.Formulario'
      IdTipoEstado:
        $ref: '#/definitions/models.TipoEstado'
      NombreCampo:
        type: string
  models.Formulario:
    title: Formulario
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.TipoEstado:
    title: TipoEstado
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
tags:
- name: tipo_estado
  description: |
    TipoEstadoController operations for TipoEstado
- name: formulario
  description: |
    FormularioController operations for Formulario
- name: campo
  description: |
    CampoController operations for Campo
